import type { Pdca } from "@/data/pdca";
import type { PdcaDialogState } from "../hooks/use_pdca_dialog_state";
import { format_date_to_string, parse_date_string } from "./date_helpers";

export const build_pdca_payload = (
  current_pdca: Pdca,
  state: PdcaDialogState,
  computed_progress: number,
): Pdca => {
  const is_no_limit_date =
    current_pdca.fechaFinalizacion === "Sin límite" ||
    current_pdca.fechaFinalizacion === "Sin lÃƒÆ’Ã‚Â­mite" ||
    current_pdca.fechaFinalizacion === "Sin lÃ­mite";

  return {
    ...current_pdca,
    titulo: state.title_value,
    area: state.area_value,
    fase: state.active_tab,
    problema: state.problem_value,
    causaRaiz: state.root_cause_value,
    acciones: state.action_items,
    targetVsActual: state.target_vs_actual,
    targetVsActualUnit: state.target_vs_actual_unit,
    targetVsActualTitle: state.target_vs_actual_title,
    targetVsActualYmin: state.target_vs_actual_ymin,
    targetVsActualYmax: state.target_vs_actual_ymax,
    kpiFinalResultData: state.kpi_final_result_data,
    kpiFinalResultUnit: state.kpi_final_result_unit,
    gembaFinalImage: state.gemba_final_image,
    gembaFinalImages: state.gemba_final_images,
    evidencias: state.evidence_files,
    kpiDocuments: state.kpi_document_files,
    paretoDataMap: state.pareto_data_map,
    paretoDrillDowns: state.pareto_drill_downs,
    paretoUnit: state.pareto_unit,
    paretoTitles: state.pareto_titles,
    vpoCheckpoints: state.vpo_checkpoints,
    definicionMeta: state.definition_goal,
    participantes: state.participants_data,
    equipo: state.team_members,
    ishikawas: state.ishikawas,
    fiveWhysTables: state.five_whys_tables,
    impactMatrix: state.impact_matrix,
    hasFlavorCorrelation: state.has_flavor_correlation,
    flavorCorrelationData: state.flavor_correlation_data,
    statisticalAnalysisFiles: state.statistical_analysis_files,
    hasGopThemes: state.has_gop_themes,
    gopThemesData: state.gop_themes_data,
    processMappingImage: state.process_mapping_files?.[0] || null,
    processMappingFiles: state.process_mapping_files,
    sipocMapFiles: state.sipoc_map_files,
    problemTimelineOption: state.problem_timeline_option,
    problemTimelineFilter: state.problem_timeline_filter,
    problemTimelineEvents: state.problem_timeline_events,
    itfR2d2Evaluation: state.itf_r2d2_evaluation,
    baselineImage: state.baseline_image,
    tablaEstandarizacion: state.tabla_estandarizacion,
    tablaEstandarizacionVpo: state.tabla_estandarizacion_vpo,
    resultadosFinales: state.resultados_finales,
    kpiTreeFocoImage: state.kpi_tree_foco_image,
    evidenciasSolucion: state.evidencias_solucion,
    hasMapeoProceso: state.has_mapeo_proceso,
    mapeoProcesoImage: state.mapeo_proceso_image,
    mapeoProcesoDesc: state.mapeo_proceso_desc || undefined,
    rendimiento_actual_pis: state.rendimiento_actual_pis,
    rendimiento_actual_image: state.rendimiento_actual_image,
    coleccionDatos: state.coleccion_datos,
    especificacionProcesosText: state.especificacion_procesos_text ?? undefined,
    especificacionProcesosImage: state.especificacion_procesos_image,
    finalTimeSeriesTitle: state.final_time_series_title,
    finalTimeSeriesData: state.final_time_series_data,
    finalTimeSeriesUnit: state.final_time_series_unit,
    finalTimeSeriesYmin: state.final_time_series_ymin,
    finalTimeSeriesYmax: state.final_time_series_ymax,
    currentTimesTitle: state.current_times_title,
    ishikawaConceptos: state.ishikawa_conceptos,
    informacionAdicionalFiles: state.informacion_adicional_files,
    vozConsumidor: state.voz_consumidor,
    analisisRiesgosProyecto: state.analisis_riesgos_proyecto,
    conclusionesCausaRaiz: state.conclusiones_causa_raiz,
    pruebasEjecutadas: state.pruebas_ejecutadas,
    nuevoPerformance: state.nuevo_performance,
    nuevo_performance_image: state.nuevo_performance_image,
    nuevo_pareto_image: state.nuevo_pareto_image,
    nuevo_pareto_drill_downs: state.nuevo_pareto_drill_downs,
    nuevo_pareto_data_map: state.nuevo_pareto_data_map,
    nuevo_pareto_unit: state.nuevo_pareto_unit,
    nuevo_pareto_titles: state.nuevo_pareto_titles,
    nueva_correlacion_image: state.nueva_correlacion_image,
    has_nueva_correlacion: state.has_nueva_correlacion,
    nueva_correlacion_data: state.nueva_correlacion_data,
    analisisRiesgosEstandarizacion: state.analisis_riesgos_estandarizacion,
    conclusionesFinales: state.conclusiones_finales,
    conclusionesStoryboardImage: state.conclusiones_storyboard_image,
    conclusionesKpiData: state.conclusiones_kpi_data ?? undefined,
    conclusionesPiItems: state.conclusiones_pi_items ?? undefined,
    sops_documentos_image: state.sops_documentos_image,
    plan_entrenamiento_image: state.plan_entrenamiento_image,
    plan_control_image: state.plan_control_image,
    lecciones_aprendidas: state.lecciones_aprendidas,
    benchmarkImage: state.benchmark_image,
    comentarios: state.comments_list,
    historial: state.history_events,
    completedSteps: Array.from(state.completed_steps),
    naSteps: Array.from(state.na_steps),
    completedPhases: Array.from(state.completed_phases),
    progreso: computed_progress,
    fechaFinalizacion: state.deadline_date
      ? format_date_to_string(state.deadline_date)
      : is_no_limit_date
        ? "Sin límite"
        : current_pdca.fechaFinalizacion && !parse_date_string(current_pdca.fechaFinalizacion)
          ? current_pdca.fechaFinalizacion
          : "",
    autor: state.author_name,
    autorEmail: state.author_email,
    asignados: state.assigned_users,
    actualizado: new Date().toLocaleDateString("es-ES", {
      day: "numeric",
      month: "short",
      year: "numeric",
    }),
  };
};
